[app]
name = "Exploding Fist"
category = "Badge"

[entry]
class = "Wotef"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-wotef"
description = "Some kung-fu on your badge"
version = "0.0.2"
